### ISSUE TITLE
MQTT Setup Questions

### ISSUE THREAD

**Issue by ex725** [Sunoo/homebridge-dafang-mqtt-republish#1]
Do I need to make a change here?

![image](https://user-images.githubusercontent.com/56446241/86623716-afaef800-bfca-11ea-8bc2-fc4bbe747bd5.png)

**Comment by Sunoo** [comment]
You'll need to set up an MQTT client somewhere (I personally recommend installing Mosquitto on the same system you run Homebridge on), then set the HOST value to point to that. You can also set LOCATION and DEVICE_NAME to change the topic it publishes to, by default it will publish to `myhome/dafang`.

I plan to try to write up some decent instructions after work today, but if you have any questions, I'm happy to try to help.

**Comment by ex725** [comment]
I'm ignorant about these things.
if you can write the instructions exactly, I can follow them one by one.
thanks in advance for that.

**Comment by Sunoo** [comment]
Okay, give me a few hours to finish working my day job and get something written up, and I'll reply here once I have that done.

**Comment by ex725** [comment]
Thank you.

**Comment by Sunoo** [comment]
Okay, I've written up a wiki page that includes fairly detailed instructions: https://github.com/Sunoo/homebridge-dafang-mqtt-republish/wiki/Configuring-Dafang-Hacks-Cameras-for-Homebridge

Please let me know if this is enough for you to get things configured. I'm happy to try to assist further if needed.

**Comment by ex725** [comment]
that's pretty revealing. Thanks a lot
I'll try when I get home

**Comment by ex725** [comment]
thanks for your supports worked smoothly

**Comment by Sunoo** [comment]
Fantastic, glad I could help.

**Comment by ex725** [comment]
notifications come a little late
is that normal ?
it comes after coming out of the camera's dial

**Comment by Sunoo** [comment]
How late? In my testing, the alerts came almost the instant I waved my hand in front of the camera.

That said, if there is a delay, it’s probably your network or something else I have no control over, as there is no real programmed in delay or buffering in either of the plugins. Just the cooldown in this plugin, which wouldn’t delay the start of the initial motion alert.

**Comment by ex725** [comment]
about 15 seconds after the action

![image](https://user-images.githubusercontent.com/56446241/86846731-f62c5180-c0b3-11ea-9f76-50af5b8cdbea.png)


       {
            "mqtt": "127.0.0.1",
            "topic": "homebridge/motion",
            "cameras": [
                {
                    "name": "Giris",
                    "motion": true,
                    "motionTimeout": -1,
                    "videoConfig": {
                        "source": "-re -i rtsp://192.168.1.112:8554/unicast",
                        "stillImageSource": "-i rtsp://192.168.1.112:8554/unicast",
                        "vcodec": "copy",
                        "audio": false,
                        "debug": true
                    }
                }
            ],
            "platform": "Camera-ffmpeg"
        },
        {
            "cameras": [
                {
                    "name": "Giris",
                    "dafang_topic": "myhome/dafang",
                    "homebridge_topic": "homebridge/motion",
                    "cooldown": 30
                }
            ],
            "name": "Dafang MQTT",
            "server": "127.0.0.1",
            "port": 1883,
            "platform": "dafangMqtt"
        }
    ]
}

**Comment by Sunoo** [comment]
15 seconds is a lot, and certainly nothing in either this plugin or Camera FFmpeg would explain that.

If you run Homebridge in debug mode (if using Config UI X, the option is under Homebridge Settings then Startup Options), then watch the log (the squiggly line in Config UI X), do the log entries about seeing motion messages happen quickly, or are any of them also delayed?

You could also make sure that the camera is seeing the motion by going to the camera’s Motion Detection settings and turning on “Display motion indicator”. Then, while watching the video stream a colored dot will appear in the image when the camera see’s motion. If that dot doesn’t appear, it won’t send any messages to Homebridge.

**Comment by ex725** [comment]
as you said everything
do you want to connect and check

**Comment by Sunoo** [comment]
I’m sorry, I don’t understand what you mean.

**Comment by ex725** [comment]
can you contact and check with teamviewer

**Comment by Sunoo** [comment]
I’m sorry, I’m just not really comfortable doing that.

**Comment by ex725** [comment]
thanks for your help
