### ISSUE TITLE
How to set up an MQTT broker or is this plugin a broker itself?

### ISSUE THREAD

**Issue by Bittabola** [Sunoo/homebridge-dafang-mqtt-republish#169]
Hi all,

I am a complete newbie and I need help. My goal is to receive a notification when the camera detects a motion so I can use it for automations.

I installed the firmware for the Wyze V2 camer and I am able to access in using the local IP address. I set it up as explained here: https://github.com/sahilchaddha/homebridge-dafang/blob/master/Setup_MQTT.md. I also have this plugin installed and configured.

Do I need a separate MQTT broker install? I do have MQTT-Things installed but have no idea how to configure it.

Any help would be appreciated. Thank you!

**Comment by Sunoo** [comment]
This plugin does not include its own broker, you'll need to install one separately. I recommend Mosquitto.

That said, if you only care about motion, you don't need this plugin at all, homebridge-camera-ffmpeg has MQTT support for motion, and that would be the best place to configure that.

This plugin is focused on the other features of the camera exposed through MQTT.
