### ISSUE TITLE
Feature request from homebridge-dafang

### ISSUE THREAD

**Issue by MrAndersonMD** [Sunoo/homebridge-dafang-mqtt-republish#21]
Hi, I'm having serious problems with rtsp service on Xiaomi Xiaofang 1S. Rtsp service suddenly gets killed, the only way to get it work again is rebooting or restarting rtsp process login at camera web UI.

It will be helpful if you implement some "Accessories" like it's done on homebridge-dafang plugin, like "remountSwitch", ""resetFFMPEG", "rtspSwitch" and "restartSwitch". With that implemented you can add an automation at Home app, so like every 3 hours, rtsp service is restarted.

It seems it's the only solution for rtsp service issue.

Thanks in advance

**Comment by Sunoo** [comment]
Version 2.1.1 adds these switches.
