### ISSUE TITLE
Xiaofang 1S not reporting any motion via notification

### ISSUE THREAD

**Issue by ahmadnazirafiq** [Sunoo/homebridge-dafang-mqtt-republish#23]
I've followed the same config as stated, enabled notifications for this device on my phone, but I'm not getting any notification for motion detection despite having it turned on via camera's IP site.

![Screenshot 2020-08-24 at 7 24 45 PM](https://user-images.githubusercontent.com/66505845/91039779-c3c4bc80-e63f-11ea-93b4-58c0fc09f573.png)

I also found this toggle refused to turn on. After I turned it on, it goes back off again after refreshing the page.

**Comment by Sunoo** [comment]
Which toggle? It should be the "enable motion detection" that you need to enable, not "enable motion tracking" which only matters for cameras with pan/tilt.

**Comment by ahmadnazirafiq** [comment]
I’ve tried enabling it and save. But after refreshing the page, the box was unchecked again.

**Comment by Sunoo** [comment]
@ahmadnazirafiq Ah, I see, yea, that seems to be a bug with Dafang Hacks that I've also seen. The setting does seem to save even though the UI shows it wrong. You can see it under 'Camera Controls'. If you aren't seeing motion alerts, make sure you have 'Motion - MQTT Message' turned on, and your MQTT settings set up correctly.

**Comment by ahmadnazirafiq** [comment]
I followed your exact setup tho. I have no idea what else to adjust. Hmm. ![DC518EF3-331B-44C7-B839-FB599980EC0E](https://user-images.githubusercontent.com/66505845/91068659-309f7d00-e667-11ea-9453-55e25f9a1023.png)

**Comment by Sunoo** [comment]
That looks good... what does your `/system/sdcard/config/mqtt.conf` file look like? Also, I don't remember if I mentioned it, but I'm pretty sure you need to reboot the camera after updating that file.

**Comment by ahmadnazirafiq** [comment]
Here's mqtt.conf file looks like:

`############################################################
# edit this file and move it to /system/sdcard/config/mqtt.conf #
############################################################

export LD_LIBRARY_PATH='/thirdlib:/system/lib:/system/sdcard/lib'

# Options for mosquitto_sub & mosquitto_pub
#USER=mqtt-user
#PASS=mqtt-password
HOST=192.168.1.127
PORT=1883

# Define a location
LOCATION="Foyer"

# Define device name
DEVICE_NAME="Entrance"

# Define the base topic used by the camera
# send a message to myhome/dafang/set with the payload help for help.
# Results will be placed in myhome/dafang/${command} or topic/dafang/error - so please subscribe topic/dafang/# for testing purposes
TOPIC="$LOCATION/$DEVICE_NAME"

# Define an autodiscovery prefix, if autodiscovery is desired:
# AUTODISCOVERY_PREFIX="homeassistant"

# Define additional options for Mosquitto here.
# For example --cafile /system/sdcard/config/DST_Root_CA_X3.pem --tls-version tlsv1
# or use a special id to connect to brokers like azure
MOSQUITTOOPTS=""

# Add options for mosquitto_pub like -r for retaining messages
MOSQUITTOPUBOPTS=""

# Send a mqtt statusupdate every n seconds
STATUSINTERVAL=30

# Define whether you would like to have light level exposed (by hardware sensor og virtual calcuations).
# If the device doesn't come with a hardware sensor, your only option is to use 'virtual'.
# 
#  Options:
#     hw = Use 'hw' if the device has build in hardware light sensor. For more details, see . See issue eg. #1120 for more details...
#     virtual = Use 'virtual' calculations, based on the lightlevel on the image, also known as ISP exposure (from /proc/jz/isp/isp_info)
#     false = Use 'false' (default) to DISABLE the topic (It will not publishing details about light level)
LIGHT_SENSOR="false"
`

**Comment by Sunoo** [comment]
The trick is to put three backticks at the start and end for multiline code.

That looks good though, assuming you have `Foyer/Entrance` configured as `dafang_topic` in your Homebridge config and you have Mosquitto or some other MQTT broker running on 192.168.1.127

**Comment by ahmadnazirafiq** [comment]
Here's my Homebridge config though. I'm really stuck as to why HomeKit doesn't report any motion detected as the camera itself detects it (a red dot on the live feed appears).

{
            "name": "Camera FFmpeg",
            "mqtt": "127.0.0.1",
            "portmqtt": 1883,
            "topic": "homebridge",
            "cameras": [
                {
                    "name": "Entrance",
                    "manufacturer": "Xiaomi",
                    "model": "Xiaofang 1S",
                    "serialNumber": "2016DP5557",
                    "motion": true,
                    "motionTimeout": 0,
                    "videoConfig": {
                        "source": "-fflags +discardcorrupt -i rtsp://192.168.1.227:8554/unicast",
                        "stillImageSource": "-i https://root:ismart12@192.168.1.227/cgi-bin/currentpic.cgi",
                        "maxStreams": 2,
                        "vcodec": "copy",
                        "packetSize": 564,
                        "audio": true
                    }
                }
            ],
            "platform": "Camera-ffmpeg"
        },
        {
            "cameras": [
                {
                    "name": "Entrance",
                    "dafang_topic": "Foyer/Entrance",
                    "cooldown": 30
                }
            ],
            "name": "Dafang MQTT",
            "server": "127.0.0.1",
            "port": 1883,
            "homebridge_topic": "homebridge/motion",
            "platform": "dafangMqtt"
        }

>>>

**Comment by Sunoo** [comment]
I'm assuming you're running Homebridge on the same device as your MQTT broker. So that looks good.

Maybe I misunderstood the problem. Is this just a notification problem, or is motion not making it into HomeKit? You should be able to tell if you watch the motion detector in the Home app. If motion is making it to HomeKit, you'll see the motion sensor turn on and off.

**Comment by ahmadnazirafiq** [comment]
The motion doesn't make it into HomeKit. You can see screenshot of the Home app there's a red dot indicating the camera recognised the motion but Home app doesn't reflect it.

![IMG_4731](https://user-images.githubusercontent.com/66505845/91182668-0c05dc80-e71d-11ea-9d65-28c81078bc12.jpg)
![IMG_4732](https://user-images.githubusercontent.com/66505845/91182683-11fbbd80-e71d-11ea-9caf-f02db2fecc26.jpg)

**Comment by Sunoo** [comment]
If you watch the MQTT traffic by running `mosquitto_sub -v -t '#'` on the device you have the broker running on, do you see the motion messages come through?

**Comment by ahmadnazirafiq** [comment]
Is this what you meant?

![Screenshot 2020-08-25 at 10 00 07 PM](https://user-images.githubusercontent.com/66505845/91183804-7b300080-e71e-11ea-81e8-98843d464e1b.png)

**Comment by Sunoo** [comment]
Interesting, I'm not seeing any motion alerts in there at all. Maybe your motion isn't actually on in Dafang Hacks then. Might be worth opening an issue with them.

**Comment by ahmadnazirafiq** [comment]
Yeah, that's what I thought too, considering the Motion Detection checkbox doesn't save in Dafang Hacks page.

Yep, will do. Thanks a lot for your help though.

**Comment by Sunoo** [comment]
No problem. I'll close this out for now, but if you get that part resolved but are still having trouble, feel free to open another and I'll see what I can do.
