### ISSUE TITLE
Saving snapshots and recordings

### ISSUE THREAD

**Issue by DietShasta** [Sunoo/homebridge-dafang-mqtt-republish#31]
I recently found this plugin after using the "Homebridge Dafang" plugin for a while now. It's been pretty reliable for me despite a few quirks. Unfortunately, it looks like it has been abandoned. 

I did notice that in Homebridge Dafang, you can set where your snapshots and videos are saved to. For instance, I was saving my files to my icloud drive. In homebridge-dafang-mqtt-republish, there doesn't seem to be this setting and will save recordings onto the sdcard. I have no idea where snapshots are saved to.

Is there a setting where I can set where snapshots and recordings are saved to and I just missed it?

Thank you!

**Comment by Sunoo** [comment]
This plugin just sends commands to the camera, so for snapshot and video, it just tells the camera to take a picture or start recording. If I remember correctly, that location is always the DCIM folder on the SD card.

**Comment by DietShasta** [comment]
I found the recordings in /system/sdcard/dcim/recordings but they are being saved as h264 files. I'm also having a hard time finding where snapshots are saved.

I'm trying to find the best way to handle videos and images when motion is detected. If I use a homekit automation that starts a recording and takes an image when the camera detects motion, then the files go into hard to reach directories. The other option is to have dafang hacks do it directly. The customizations can be edited in /system/sdcard/config/motion.conf. The only problem is there doesn't seem to be a way to turn off motion detection from homebridge-dafang-mqtt-republish when I just want to view livestreams.

**Comment by Sunoo** [comment]
Since I'm passing the commands off to the camera, I would assume it'd be a fairly similar result as if the camera did it itself.

I could probably add a switch to enable/disable motion detection, but I don't understand why you would need to disable it to watch a camera stream?

**Comment by DietShasta** [comment]
I'm not sure how most users are recording the videos, but I'd guess they are using Dafang Hacks built in motion detection automation. In motion.conf, you can have video and images save to user settable file location on the sd card, FTPed, telegramed, emailed, or SMBed. I'm not sure how many are actually kicking off recordings and taking images manually from the camera. The file format and file locations aren't user friendly and easily accessable. 

So if I do use dafang hacks built in motion detection automation, then it will constantly be saving files when motion is detected even when I just want to view the livestream. Enabling/disabling motion detection will prevent that.

**Comment by Sunoo** [comment]
So adding a switch to enable/disable the camera's motion detection will resolve the issue you're having? If so, I can add one.

**Comment by DietShasta** [comment]
I've been going back and forth between homebridge-dafang-mqtt-republish and homebridge-dafang. I ran into a couple issues with how dafang hacks handles videos on motion detection events. SMB just doesn't work for me. FTP does work and at first it feels like a good solution for getting the files off the sd card automatically except the videos are avi files that are 1 fps!  And the file size seem abnormally large. In dafang hacks detectionOn.sh script it actually says something about the bandwidth limitations so it was limited to 1 fps. For some reason homebridge-dafang got around the limitation though and can save normal mp4 files at higher fps onto the computer homebridge is installed on.

**Comment by Sunoo** [comment]
If I remember correctly, homebridge-dafang actually records the video stream coming from the camera. This is a feature I have no intention of adding to this plugin, especially given that the video parts are handled by homebridge-camera-ffmpeg.

**Comment by DietShasta** [comment]
How are you managing motion detection videos and stills with your set up?

**Comment by Sunoo** [comment]
I personally don’t use them, so I’m not overly familiar with their functionality.
