### ISSUE TITLE
HomeKit not getting motion detection

### ISSUE THREAD

**Issue by ahmadnazirafiq** [Sunoo/homebridge-dafang-mqtt-republish#42]
Hi, I've installed this hack successfully for both Xiaofang and Dafang. However, despite troubleshooting and opening tickets to Dafang Hacks (not getting response), I'm still not getting any motion detection notification on the Home app.

I have enabled Motion -MQTT Message, enabled notification on the Home app. When I run mosquitto_sub -v -t '#' command I believe the motion was recognized by the camera.

![Screenshot 2020-09-14 at 10 53 03 AM](https://user-images.githubusercontent.com/66505845/93038982-f4b17380-f678-11ea-8ff7-652c97bf968a.png)

I'm really stuck here, as these cameras were recently blocked by Xiaomi due to geographical restrictions :(

**Comment by Sunoo** [comment]
Please share your config.json, looks like it probably isn’t set up correctly.

**Comment by Sunoo** [comment]
Actually, looks like something is up with the MQTT configuration on your camera too. Seems like you don’t have any topic set at all, and motion is being published to just `/motion`.

**Comment by ahmadnazirafiq** [comment]
Here is my config.json...


 {
            "name": "Camera FFmpeg",
            "mqtt": "127.0.0.1",
            "portmqtt": 1883,
            "topic": "homebridge/motion",
            "cameras": [
                {
                    "name": "Entrance",
                    "manufacturer": "Xiaomi",
                    "model": "Xiaofang 1S",
                    "serialNumber": "2016DP5557",
                    "firmwareRevision": "5.6.2.197",
                    "motion": true,
                    "motionTimeout": 0,
                    "videoConfig": {
                        "source": "-re -i rtsp://192.168.1.227:8554/unicast",
                        "stillImageSource": "-i https://root:ismart12@192.168.1.227/cgi-bin/currentpic.cgi",
                        "maxStreams": 2,
                        "vcodec": "copy",
                        "packetSize": 564,
                        "audio": true
                    }
                },
                {
                    "name": "Shelf",
                    "manufacturer": "Xiaomi",
                    "model": "Dafang",
                    "serialNumber": "2017DP3894",
                    "firmwareRevision": "5.5.1_0426",
                    "motion": true,
                    "videoConfig": {
                        "source": "-re -i rtsp://192.168.1.206:8554/unicast",
                        "audio": true
                    }
                }
            ],
            "platform": "Camera-ffmpeg"
        },
        {
            "cameras": [
                {
                    "name": "Entrance",
                    "dafang_topic": "Foyer/Entrance",
                    "cooldown": 30,
                    "accessories": {
                        "rtsp_h264_server": true
                    }
                },
                {
                    "name": "Shelf",
                    "dafang_topic": "Den/Shelf",
                    "cooldown": 30,
                    "accessories": {
                        "rtsp_h264_server": true
                    }
                }
            ],
            "name": "Camera FFmpeg",
            "server": "127.0.0.1",
            "port": 1883,
            "homebridge_topic": "homebridge/motion",
            "platform": "dafangMqtt"
        }

**Comment by ahmadnazirafiq** [comment]
Forgive me if its too tiny to see. I suck at this :(

![Screenshot 2020-09-14 at 11 21 06 AM](https://user-images.githubusercontent.com/66505845/93040378-7525a380-f67c-11ea-902e-3ea75e464efb.png)

**Comment by Sunoo** [comment]
That all looks about right to me, the problem must be on the configuration on the cameras themselves then.

I’m really not sure why you’re seeing the control stuff coming through on the proper topic, but not motion though.

**Comment by ahmadnazirafiq** [comment]
Do you think the MQTT is the one to blame? I followed the official Dafang Hacks guide (https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/master/hacks/install_cfw.md) to install the CFM for both cameras, but neither has motion detection enabled. Any more things I should look out to?

Or was it the microSD card that caused this? As I am using 16GB card, deleted the partition and set with only 512MB active.

**Comment by ahmadnazirafiq** [comment]
Issue resolved. Thanks!
