### ISSUE TITLE
Add "recalibrate" accessory switch?

### ISSUE THREAD

**Issue by jlg89** [Sunoo/homebridge-dafang-mqtt-republish#58]
Could you add a "recalibrate" accessory switch, that would run "/cgi-bin/action.cgi?cmd=motor_calibrate" on the camera?

**Comment by Sunoo** [comment]
If I can do it with MQTT, I’ll take a look.

**Comment by jlg89** [comment]
I know homebridge-dafang does it, but that plugin hasn't had any love in awhile, and your plugin in conjunction with camera-ffmpeg is a better solution at this point.

**Comment by Sunoo** [comment]
I’m pretty sure that plugin only talked to the camera through MQTT, so it should be doable.

**Comment by jlg89** [comment]
Looks like it does this:

this.publishToMQTT('/motors/set', 'calibrate')

**Comment by Sunoo** [comment]
Perfect, should be simple to add.

**Comment by Sunoo** [comment]
Sorry for the delay, this will be in the next release, which should be within the next few days.

**Comment by jlg89** [comment]
I'll be happy to have it whenever you get to it, absolutely no rush. I hope you're staying warm!

**Comment by Sunoo** [comment]
Added in v2.2.0
